// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"landing\"><section class=\"landing__hero\"><p class=\"landing__eyebrow\">Slack &amp; Atlassian, in your UI</p><h2 class=\"landing__title\">Rich profile and issue links for any web app</h2><p class=\"landing__lead\">Omnitar connects to your workspace, then serves a small script you drop into HTML, React, Rails, or anything else that runs in a browser. Two custom elements handle hover cards for people and Jira issues.</p><div class=\"landing__cta\"><wa-button href=\"/auth/slack\" variant=\"brand\" size=\"large\"><wa-icon slot=\"prefix\" name=\"slack\" family=\"brands\"></wa-icon> Get started with Slack</wa-button> <wa-button href=\"/auth/atlassian\" variant=\"brand\" size=\"large\"><wa-icon slot=\"prefix\" name=\"atlassian\" family=\"brands\"></wa-icon> Get started with Atlassian</wa-button></div><p class=\"landing__cta-hint\">Sign in to connect a workspace. Your account page includes the script tag with your account ID—paste it once, then use the elements anywhere on your site.</p></section><section class=\"landing__components\"><h3 class=\"landing__section-title\">Web components</h3><p class=\"landing__section-lead\">After you add <code>&lt;script type=&quot;module&quot; src=&quot;…/webcomponent.js&quot;&gt;&lt;/script&gt;</code> , these tags work like native HTML.</p><div class=\"landing__grid\"><wa-card class=\"landing__card\"><div slot=\"header\"><h4><code>&lt;omnitar-profile&gt;</code></h4></div><p>Turn an email or display name into a link with an optional hover card: avatar, full name, and custom profile fields from Slack.</p><wa-button slot=\"footer\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue("/docs/?path=/docs/web-components-omnitar-profile--docs")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `index.templ`, Line: 41, Col: 94}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" variant=\"primary\">View docs &amp; examples <wa-icon slot=\"suffix\" name=\"arrow-up-right-from-square\"></wa-icon></wa-button></wa-card> <wa-card class=\"landing__card\"><div slot=\"header\"><h4><code>&lt;omnitar-issue&gt;</code></h4></div><p>Render Jira issue keys with status, type, and assignee on hover—ideal for changelogs, runbooks, and internal tools.</p><wa-button slot=\"footer\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue("/docs/?path=/docs/web-components-omnitar-issue--docs")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `index.templ`, Line: 53, Col: 92}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" variant=\"primary\">View docs &amp; examples <wa-icon slot=\"suffix\" name=\"arrow-up-right-from-square\"></wa-icon></wa-button></wa-card></div></section><section class=\"landing__steps\"><h3 class=\"landing__section-title\">How it works</h3><ol class=\"landing__step-list\"><li><strong>Connect</strong> <span>— Authenticate with Slack, Atlassian, or both so Omnitar can read directory and issue data on your behalf.</span></li><li><strong>Embed</strong> <span>— Copy the module script from your account page; it is scoped to your account UUID.</span></li><li><strong>Compose</strong> <span>— Use the custom elements in your markup; full API and live examples are in the <a href=\"/docs\">component docs</a>.</span></li></ol></section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
