// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script type=\"module\" src=\"/slack/E0AFSMB25HU/webcomponent.js\"></script> <h2 id=\"quick-start\" class=\"anchor-heading\">Quick Start</h2><p>Add the following code to your page.</p><!-- prettier-ignore --> <p><copy-paste>&lt;script type=&quot;module&quot; src=&quot;")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(BaseURL(ctx))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `index.templ`, Line: 9, Col: 76}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "/slack/E0AFSMB25HU/webcomponent.js&quot;&gt;&lt;/script&gt;</copy-paste></p><!-- /prettier-ignore --> <p>Replace <mark>E0AFSMB25HU</mark> with your slack team ID</p><p>Then add a omnitar-card element with an email attribute to your page</p><!-- prettier-ignore --> <p><copy-paste>&lt;omnitar-card email=&quot;slack@gavinmogan.com&quot;&gt;halkeye&lt;/omnitar-card&gt;</copy-paste></p><!-- /prettier-ignore --> <h2>Examples</h2><wa-tab-group><wa-tab panel=\"active\">Active User</wa-tab> <wa-tab panel=\"inactive\">Invalid/Inactive User</wa-tab> <wa-tab-panel name=\"active\" active><p>Is successfully able to find a profile for the given email</p><p><b>Example:</b> <omnitar-card email=\"slack@gavinmogan.com\">halkeye</omnitar-card></p><p>Assuming that user is on your slack, you should get a nice element with full name and a nice little profile card on hover</p></wa-tab-panel> <wa-tab-panel name=\"inactive\" active><p>If no matching profile can be found (bad data, expired, etc)</p><p><b>Example:</b> <omnitar-card email=\"fake@fake.com\">user1234</omnitar-card></p><p>Will show the original tag value, but without any popups</p></wa-tab-panel></wa-tab-group>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
